#!/usr/bin/env bash

# Set the installation folder if not set
: ${HOME=$(eval echo ~)};
: ${WN_PATH="$HOME/wagglenet-wn"};

if [ "$1" = "update" ]; then
	echo "Updating wn. Git pulling on myself."
	cd $WN_PATH;
	git fetch --all;
	git reset --hard origin/master;
	exit 0;
fi

source $WN_PATH/venv/bin/activate;
python $WN_PATH/main.py;
