#!/usr/bin/env bash

# Set the installation folder if not set
: ${HOME=$(eval echo ~)};
: ${WN_PATH="$HOME/wagglenet-wn"};

if [ "$1" = "update" ]; then
	echo "Updating wn by Git pulling on myself."
	cd $WN_PATH;
	sh install.sh;
	exit 0;
else
	cd $WN_PATH;
	source $WN_PATH/venv/bin/activate;
	python $WN_PATH/main.py "$@";
fi
