actions:
  init_env:
    - commands:
      - virtualenv -p python3.6 venv
      - source venv/bin/activate
      - pip install -r requirements.txt
  init_db:
    - commands:
      - source venv/bin/activate
      - python manage.py db upgrade
  update_env:
    - commands:
      - source venv/bin/activate
      - pip install -r requirements.txt
  update_db:
    - commands:
      - source venv/bin/activate
      - python manage.py db upgrade
